# Generated by Django 4.2.13 on 2025-07-26 21:20

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookshelf", "0004_book_alter_customuser_email_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Book",
        ),
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
