# Generated by Django 4.2.13 on 2025-07-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookshelf", "0006_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
    ]
