# Generated by Django 4.2.13 on 2025-07-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0004_userprofile_delete_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('librarian', 'Librarian'), ('member', 'Member')], max_length=20),
        ),
    ]
