# Generated by Django 4.2.13 on 2025-07-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0006_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('canaddbook', 'Can add book'), ('canchangebook', 'Can change book'), ('candeletebook', 'Can delete book')]},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
